# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'shamrock:$(build.buildId)'

steps:

- script: docker run --rm --publish 5432:5432 --name build-postgres -e POSTGRES_USER=hibernate_orm_test -e POSTGRES_PASSWORD=hibernate_orm_test -e POSTGRES_DB=hibernate_orm_test -d postgres:10.5
  displayName: 'start postgres'

- task: Maven@3
  displayName: 'Maven Build'
  inputs:
    goals: 'install'
    options: '-Dnative-image.docker-build -Dno-postgres -Dnative-image.xmx=4g'

- script: |
    docker build -f docker/strict-example/Dockerfile -t jtgdocker1/shamrock-strict-example examples/strict/
    docker login -u jtgdocker1 -p uEo-NTv-5YT-kk6
    docker push jtgdocker1/shamrock-strict-example
    docker logout
  displayName: Publishing Strict Example Container Image
